# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release   
    - name: Auth github nuget
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/vovanreksi2/index.json"
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
    - name: PushGithub
      run: dotnet nuget push src/Mailtrap.SDK/**/*.nupkg --no-symbols --skip-duplicate --api-key ${{ secrets.MAILTRAP_NUGET_SECRET }} --source "github"
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}